---
title: "my solution to inclass exercise"
author: "Keren Xu"
date: "2/9/2020"
output:
  rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# a function we will work with
F1<-function(x){
  return(c(x^2,2*x)) 
  # note that the function returns two numbers. 
  # The first is f(x); 
  # the second is the derivative, f'(x)
}

#define a function F2(x)=sin(x)
F2<-function(x){
  return(c(sin(x), cos(x))) 
  # note that the function returns two numbers. 
  # The first is f(x); 
  # the second is the derivative, f'(x)
}
#define F3(x)=(x-2)^3-6*x
F3<-function(x){
  return(c((x-2)^3-6*x, 3*(x-2)^2-6)) 
  # note that the function returns two numbers. 
  # The first is f(x); 
  # the second is the derivative, f'(x)
}
#define F4(x)=cos(x)-x### 
# (All functions need to return f(x) and f’(x))
F4<-function(x){
  return(c(cos(x)-x, -sin(x)-1)) 
  # note that the function returns two numbers. 
  # The first is f(x); 
  # the second is the derivative, f'(x)
}

library(shape)


# Define your Newton-Raphson function  
NewtonRaphson<-function(func, StartingValue, Tolerance = 1*10^-9, MaxNumberOfIterations = 100){
  #initialize a variable, Deviation (say), to record |f(x)| so that you know how far away you are from 0. 
  #(So initialize it to some arbitrary large number)
  #Set up a counter, i, to record how many iterations you have performed. Set it equal to 0	
  # Initialize the values of x and f(x)
  i <- 0
  x <- StartingValue
  fx <- func(x)
  Deviation <- abs(fx[1])
  
  #Set up a while loop until we hit the required target accuracy or the max. number of steps
  while ((i < MaxNumberOfIterations) && (Deviation > Tolerance))
  {
    # Record the value of f(x) and f’(x), for the current x value. 

    # To be safe, check that the function and it's derivative are defined at X (either could be NaN if you are unlucky)
    if ((fx[1] == "NaN") || (fx[2] == "NaN")) {
      cat("\nFunction or derivative not defined error.\n")
      break
    }
    
    #Find the next X-value using Newton-Raphson's formula. Let's call that value X
    x <- x - fx[1]/fx[2]
    # calculate Deviation<- |f(x)-0|
    fx <- func(x)  
    Deviation <- abs(fx[1])
    # increase the value of your iteration counter
    i<-i+1
    
    # if you like, have the program write out how it is getting on
    cat(paste("\nIteration ",i,":   X=",x,"  Y=",fx[1]))
    
    # If you are feeling fancy, add some line segments to the screen to show where it just went
    # See the 'fixed points' code for a reminder of how to do that.

		
  }
  
  # output the result
  if (Deviation<Tolerance){
    cat(paste("\nFound the root point: ", x, " after ", i, "iterations"))
  }else{ 
    cat(paste("\nConvergence failure. Deviation: ",Deviation, "after ", i, 	"iterations"))}    
  
  # have the function return the answer
  return(x)
}

NewtonRaphson(F1,10,1e-3,40)
NewtonRaphson(F2,10,1e-3,40)
NewtonRaphson(F3,10,1e-3,40)
NewtonRaphson(F4,10,1e-3,40)
```

